# -*- coding: utf-8 -*-
"""23_UNAM_AI_Actividad_Laboratorio_4_4_bacterias.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0OdktX57cxUNf6TVlTZ4-7Hy_8QNauz

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 2.3}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Ayudante de laboratorio:} & Diego Eduardo Peña Villegas \\[6pt]
\textbf{Alumna:} & Santana de la Rosa Monica \\[6pt]
\textbf{Fecha de realización:} & 15/04/2026
\end{array}

</center>

# Bacterias

En un laboratorio se cultivan 2 tipos de bacteria (B1 y B2), los cuales necesitan 2 componentes químicos (X1 y X2) para sobrevivir en un frasco de cultivo. Los investigadores del laboratorio están interesados en determinar qué concentraciones de estos químicos son favorables para B1 y B2. Para esto realizaron varios cultivos con diferentes niveles de concentracidon de cada componente y se registrdo qude bacteria sobrevivido en cada uno de ellos (los resultados de estas pruebas están almacenados en el archivo bacterias.csv), en el cual las primeras 2 columnas describen los niveles de concentracidon de X1 y X2 y la última indica si B1 (valor igual a 0) o B2 (valor igual a 1) sobrevivido. A partir de los datos propocionados entrena un clasificador bayesiano ingenuo que prediga qude tipo de bacteria sobrevivirá a una determinada concentracidon. Reporta el número de predicciones correctas y erróneas usando los mismos datos de entrenamiento. Analiza el desempe~no del clasificador entrenado y explica los problemas que tiene con estos datos (pista: gráfica los datos para tener una idea de cdomo están distribuidos).

#Bibliotecas
"""

# Importacion de librerias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

"""#Preparar los datos"""

# Importacion del archivo que se nos proporciono agregandole cabeceras que no contiene
names = ['X1', 'X2', 'R']
dataset = pd.read_csv('bacterias.csv',names=names)
X = dataset.iloc[:, [0, 1]].values
y = dataset.iloc[:, 2].values
print(y)

""" #ENTENDIMIENTO DE LOS DATOS"""

#Verifico la información contenida en el dataset
#Con head, podremos visualizar los primeros
dataset.head()

#Con tail, podremos visualizar los últimos
dataset.tail()

# Siempre resulta interesante echarle un vistazo a los datos.
# Podemos ver, por ejemplo, los 10 primeros registros.
print(dataset.head(10))

#Verificamos el tipo de dato que contiene
dataset.dtypes

# descriptions
# La función describe nos ofrece una serie de valores
# como el número de registros,los valores máximos y mínimos,
# la media y algunos valores porcentuales.
dataset.describe(include="all")

# class distribution
# La función class distribution nos indica cuántas
# instancias hay de cada caso
dataset.groupby('R').size()

# Gráficas
dataset.plot(kind='line', subplots=True, layout=(2,2), sharex=False, sharey=False)
plt.show()

dataset.hist()
plt.show()

"""IMPLEMENTACIÓN DE NAIVE BAYES"""

# Division de datos para entrenamientoy prueba
#Importamos la librería

from sklearn.model_selection import train_test_split

#Separo los datos de  "train" en entrenamiento y prueba para probar los algoritmos
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Ajuste de escalas
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#Definición del algoritmo a usar
# Creacion del modelo Naive Bayes
# y entrenamiento del mismo
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()

"""#Entrenamiento"""

#Entrenamiento con el 80% que son con los 280 registros
classifier.fit(X_train, y_train)

"""#PREDICCIÓN"""

# Prediccion del conjunto de prueba de acuerdo al 20% para los entrenamientos 120 registros
y_pred = classifier.predict(X_test)

print(y_test)

print(y_pred)

#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

print("Exactitud:", metrics.accuracy_score(y_test, y_pred))

# Matriz de confusion
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

print(y_train)

print ('Precisión del modelo:')
print(classifier.score(X_train,y_train))

# Visualizacion de los datos de prueba
from matplotlib.colors import ListedColormap
X_set, y_set = X_test, y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.75, cmap = ListedColormap(["r", "b"]))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())



for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1], c = ListedColormap(["r", "b"])(i), label = j)
plt.title('Naive Bayes (Datos de prueba)')
plt.xlabel('X1')
plt.ylabel('X2')
plt.legend()
plt.show()

#Realizar las predicciones en una validación de dataset
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

NB = GaussianNB()
NB.fit(X_train, y_train)
predictions = NB.predict(X_test)
print(accuracy_score(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

"""C0,0=17 – Verdaderos Negativos, respuesta 0, predicción 0

C1,0=9 – Falsos Negativos, respuesta 1, predicción 0

C0,1=29 – Falsos Positivos, respuesta 0, predicción 1

C1,1=25 – Verdaderos Positivos, respuesta 1, predicción 1
"""

import seaborn as sns
import matplotlib.pyplot as plt

ax= plt.subplot()
sns.heatmap(cm, annot=True, ax = ax); #annot=True to annotate cells

# Etiquetas, Título and medidas
ax.set_xlabel('Etiquetas Predictivas');ax.set_ylabel('Etiquetas Verdaderas');
ax.set_title('MATRIZ DE CONFUSIÓN');
ax.xaxis.set_ticklabels(['Falsos', 'Positivos']); ax.yaxis.set_ticklabels(['Positivos', 'Falsos']);

"""# 1. Regresión Logística (Logistic Regression)
La regresión logística intentará encontrar un hiperplano (una línea, en este caso 2D) que separe las dos clases de bacterias.

¿Cómo funciona?: Calcula una combinación lineal de las entradas y le aplica la función sigmoide para obtener una probabilidad entre 0 y 1.

Limitación: Si las bacterias están distribuidas de forma circular o si una clase rodea a la otra (distribuciones no lineales), la Regresión Logística tendrá un desempeño pobre porque solo puede trazar fronteras rectas.
"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

#Entrenamiento
log_reg = LogisticRegression()
log_reg.fit(X, y)

#Prediccion
y_pred_log = log_reg.predict(X)

print("Reporte Regresion Logistica:")
print(classification_report(y, y_pred_log))

"""# 2. Máquinas de Vector de Soporte (SVM)
SVM es más robusto porque permite usar el Kernel Trick para encontrar fronteras de decisión complejas.

Kernel Lineal: Similar a la regresión logística.

Kernel RBF (Gaussiano): Crea fronteras curvas. Es muy probable que este sea el necesario para el dataset de bacterias si las concentraciones óptimas forman "nubes" o grupos cerrados.
"""

from sklearn.svm import SVC

#Entrenamiento con un Kernel RBF para capturar no-linealidades
svm_model = SVC(kernel='rbf', gamma = 'auto')
svm_model.fit(X, y)

y_pred_svm = svm_model.predict(X)

print("Reporte SVM (RBF):")
print(classification_report(y, y_pred_svm))

"""#Visualización"""

def plot_decision_boundary(model, X, y, title):
  h = 0.2 #tamaño del paso en la malla
  x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
  y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
  xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))

  Z = model.predict(np.c_[xx.ravel(), yy.ravel()])
  Z = Z.reshape(xx.shape)

  plt.contourf(xx, yy, Z, alpha=0.8)
  plt.scatter(X[:, 0], X[:, 1], c=y, edgecolors='k')
  plt.title(title)
  plt.show()

#Comparamos viisualmente
plot_decision_boundary(log_reg, X, y, "Frontera Regresión Logística")
plot_decision_boundary(svm_model, X, y, "Frontera SVM (RBF)")

"""## Análisis de Resultados

### Matriz de Confusión
La matriz de confusión obtenida fue:

[[17, 29],
 [ 9, 25]]

Donde:
- 17 son verdaderos negativos (predijo correctamente clase 0)
- 25 son verdaderos positivos (predijo correctamente clase 1)
- 29 son falsos positivos (clasificó como 1 cuando era 0)
- 9 son falsos negativos (clasificó como 0 cuando era 1)

Se observa un número alto de falsos positivos, lo que indica que el modelo tiende a clasificar incorrectamente la clase 0 como 1.

---

### Accuracy
El modelo obtuvo una exactitud de:

Accuracy = 0.525

Esto significa que solo el 52.5% de las predicciones son correctas, lo cual es bajo considerando que las clases están balanceadas (50%-50%).

---

### Precisión
Para la clase 1:
Precision ≈ 0.46

Esto indica que menos de la mitad de las predicciones positivas son correctas, lo que refleja un alto número de falsos positivos.

---

### Interpretación General
El modelo Naive Bayes tiene un desempeño bajo en este problema. Esto se debe a que los datos probablemente no cumplen el supuesto de independencia entre variables o no siguen una distribución gaussiana adecuada.

Además, la distribución de los datos parece no ser lineal, lo que afecta directamente el desempeño del modelo.

---

### Comparación con otros modelos
Se observa que modelos como SVM alcanzan una exactitud cercana al 78%, lo que indica que los datos tienen una estructura más compleja que Naive Bayes no puede capturar.

---

### Conclusión
El modelo Naive Bayes no es adecuado para este dataset, ya que presenta baja exactitud y precisión. Es necesario utilizar modelos más complejos, como SVM con kernel RBF, que puedan adaptarse mejor a distribuciones no lineales.

#Conclusión

En esta práctica aprendí que no todos los modelos funcionan bien con cualquier tipo de datos. El clasificador Naive Bayes tuvo un desempeño bajo, lo que me hizo notar que los datos no cumplen con sus supuestos. Al comparar con otros modelos, como SVM, entendí que cuando los datos no son lineales se necesitan métodos más complejos.

También vi que la matriz de confusión es útil para analizar mejor los errores, no solo la exactitud. En general, comprendí la importancia de elegir correctamente el modelo según la forma en que están distribuidos los datos.

Bibliografía

- Murphy, K. P. (2022). Probabilistic Machine Learning: An Introduction. MIT Press.
- Bishop, C. M., & Bishop, H. (2023). Deep Learning: Foundations and Concepts. Springer Nature.
- Geron, A. (2022). Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow (3rd ed.). O'Reilly Media.
- Russell, S. J., & Norvig, P. (2020). Artificial Intelligence: A Modern Approach (4th ed.). Pearson.
- Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""