# -*- coding: utf-8 -*-
"""24_UNAM_AI_Actividad_Laboratorio_4_5_spam-2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3OUgUY00nO22S52z1qTnq8zhONz-vAG

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 2.3}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Ayudante de laboratorio:} & Diego Eduardo Peña Villegas \\[6pt]
\textbf{Alumna:} & Marisol Luna Méndez \\[6pt]
\textbf{Fecha de realización:} & 25/02/2026
\end{array} 4

</center>

#Bibliotecas
"""

# Importacion de librerias
import numpy as np
from numpy import genfromtxt
import matplotlib.pyplot as plt
import pandas as pd

"""# Spam

Usando la base de datos de spam (archivo spam.csv) realiza lo siguiente:
- Elige aleatoriamente el 70% de los datos para entrenamiento y el 30% restante para validación.
- Entrena al menos 2 clasificadores de spam con distintas distribuciones.

- Emplea los clasificadores entrenados para predecir spam tanto en los datos de entrenamiento como en los de validación y reporta el porcentaje de predicciones correctas de cada clasificador

- Discute el desempeño de los diferentes clasificadores

El archivo spam.csv contiene 2001 valores por cada renglón, de los cuales los primeros 2000 representan el histograma de palabras de un correo y el último corresponde a la clase, esto es, 1 si es spam y 0 si no lo es.

#Preparar los datos
"""

# Importacion del archivo que se nos proporciono agregandole cabeceras que no contiene
names = ['correo' ]
dataset = pd.read_csv('spam.csv',names =names)
data=genfromtxt('spam.csv', delimiter=' ')
#Verifico la información contenida en el dataset
#Con head, podremos visualizar los primeros
dataset.head(5)

# Asegúrate de que el delimitador sea el correcto (espacio, coma o tabulador)
dataset = pd.read_csv('spam.csv', sep='\s+', header=None)

# Verifica la forma: debería ser (N, 2001)
print(f"Forma del dataset: {dataset.shape}")

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Suponiendo que 'dataset' ya cargó las 2001 columnas
X = dataset.iloc[:, :-1].values # Las primeras 2000 columnas
y = dataset.iloc[:, -1].values  # La última columna (clase)

# División 70% entrenamiento y 30% validación
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

# Importante para SVM, KNN y Regresión Logística: Escalamiento
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

"""#2. Implementación de los 4 Clasificadores"""

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB, BernoulliNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

#Diccionario para almacenar modelos
modelos = {
    "Logistic Regression":LogisticRegression(max_iter= 1000),
    #"SVM (Kernel RBF)": SVC(kernel='rbf', probability = True),
    #"Naive Bayes (Bernoulli)": BernoulliNB(), # Ideal para presencia o ausencia de palabras
    "KNN (k=5)": KNeighborsClassifier(n_neighbors=5)
    }

#Entrenamiento y Evaluación
for nombre, modelo in modelos.items():


    # Para naive Bayes multinomial/Bernoulli, los datos no deben estar estandarizados
    # con valores negativos. Si usas datos escalados, Logistic/SVM/KNN funcionan mejor.
    modelo.fit(X_train, y_train)

    train_acc = accuracy_score(y_train, modelo.predict(X_train))
    test_acc = accuracy_score(y_test, modelo.predict(X_test))

    print(f"{nombre}:")
    print(f"Precisión de entrenamiento:{train_acc*100:.2f}%:")
    print(f"Precisión de Validación:{test_acc*100:.2f}%\n")

nombres = []
train_results = []
test_results = []

for nombre, modelo in modelos.items():
    nombres.append(nombre)
    train_results.append(accuracy_score(y_train, modelo.predict(X_train)) * 100)
    test_results.append(accuracy_score(y_test, modelo.predict(X_test)) * 100)

x = np.arange(len(nombres))
width = 0.35

fig, ax = plt.subplots(figsize=(12, 7))
rects1 = ax.bar(x - width/2, train_results, width, label='Entrenamiento', color='#3498db')
rects2 = ax.bar(x + width/2, test_results, width, label='Validación', color='#e74c3c')

ax.set_ylabel('Precisión (%)')
ax.set_title('Desempeño de Clasificadores de Spam')
ax.set_xticks(x)
ax.set_xticklabels(nombres)
ax.set_ylim(0, 115) # Espacio para las etiquetas
ax.legend()

# Función para añadir los porcentajes sobre las barras
def label_bars(rects):
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.1f}%',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3), textcoords="offset points",
                    ha='center', va='bottom')

label_bars(rects1)
label_bars(rects2)

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.show()

#Entrenamiento y Evaluación
from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
#ax= plt.subplot()
fig, axs = plt.subplots(2, 1, figsize=(8, 5))
axs =axs.flatten()
#ax = plt.subplots(2)
for i, (nombre, modelo) in enumerate(modelos.items()):
    # Para naive Bayes multinomial/Bernoulli, los datos no deben estar estandarizados
    # con valores negativos. Si usas datos escalados, Logistic/SVM/KNN funcionan mejor.
    modelo.fit(X_train, y_train)

    train_acc = accuracy_score(y_train, modelo.predict(X_train))
    test_acc = accuracy_score(y_test, modelo.predict(X_test))


    #sns.heatmap(cm, annot=True, ax = ax); #annot=True to annotate cells
    #print(f"\n")

    print(f"{nombre}:")
    print(f"Precisión de entrenamiento:{train_acc*100:.2f}%")
    print(f"Precisión de Validación:{test_acc*100:.2f}%\n")
    print(f"\n")
    # Matriz 1: Logistic Regression (Normalizada por fila)
    ax_actual = axs[i]
    ConfusionMatrixDisplay.from_estimator(
        modelo,
        X_test,
        y_test,
        cmap='Greens',
        ax=ax_actual,
        colorbar= False
    )
    ax_actual.set_title (f"Matriz:{modelo}")
plt.tight_layout
plt.show()

"""=== ANÁLISIS DE RESULTADOS ===

A partir de la matriz de confusión obtenida:

[[TN  FP]
 [FN  TP]]

Se identifican los siguientes casos:

- Verdaderos Negativos (TN): El modelo predijo correctamente la clase 0.
- Falsos Positivos (FP): El modelo predijo clase 1 cuando en realidad era 0.
- Falsos Negativos (FN): El modelo predijo clase 0 cuando en realidad era 1.
- Verdaderos Positivos (TP): El modelo predijo correctamente la clase 1.

El Accuracy obtenido representa el porcentaje total de predicciones correctas.
En este caso, un valor cercano a 0.5 indica que el modelo apenas es mejor que
una predicción aleatoria, lo que sugiere bajo desempeño.

La Precisión mide qué tan confiables son las predicciones positivas (clase 1).
Un valor bajo de precisión indica que el modelo está generando muchos falsos positivos,
es decir, clasifica incorrectamente casos como positivos.

Observando la matriz de confusión, se puede notar que hay una cantidad considerable
de errores (FP y FN), lo que indica que el modelo no está separando bien las clases.

En particular:
- Los falsos positivos afectan directamente la precisión.
- Los falsos negativos afectan la capacidad del modelo de detectar correctamente la clase positiva.

Esto sugiere que el modelo Naive Bayes no es el más adecuado para este dataset,
probablemente porque los datos no cumplen con el supuesto de independencia entre variables
o porque la distribución de los datos no es adecuada para este modelo.

=== CONCLUSIÓN ===

El modelo presenta un desempeño bajo, con una exactitud cercana al azar
y una precisión limitada. Esto indica que no es confiable para realizar predicciones
en este problema.

Se concluye que es necesario utilizar modelos más complejos o que capturen relaciones
no lineales en los datos, como SVM o árboles de decisión, para mejorar el desempeño.

#Conclusión

En esta práctica observé que distintos clasificadores pueden tener desempeños muy diferentes en un mismo problema. La regresión logística fue el modelo más efectivo, logrando la mayor precisión tanto en entrenamiento como en validación, lo que indica que los datos son relativamente separables.

Por otro lado, modelos como Naive Bayes tuvieron menor rendimiento, probablemente porque hacen suposiciones más simples sobre los datos. En general, entendí que la elección del modelo influye mucho en los resultados y que es importante comparar varios para encontrar el más adecuado.

Bibliografía

- Murphy, K. P. (2022). Probabilistic Machine Learning: An Introduction. MIT Press.
- Bishop, C. M., & Bishop, H. (2023). Deep Learning: Foundations and Concepts. Springer Nature.
- Geron, A. (2022). Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow (3rd ed.). O'Reilly Media.
- Russell, S. J., & Norvig, P. (2020). Artificial Intelligence: A Modern Approach (4th ed.). Pearson.
- Goodfellow, I., Bengio, Y., & Courville, A. (2016). Deep Learning. MIT Press.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""