# -*- coding: utf-8 -*-
"""25_UNAM_AI_Actividad_Laboratorio_4_6_cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E5l44oyqN4BSWPf4EnPfbnsORNVykExK

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 4.6}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Ayudante de laboratorio:} & Diego Eduardo Peña Villegas \\[6pt]
\textbf{Alumnos:} & Elizalde Maza Jesús Eduardo 321031686 \\[6pt]
& Ledesma Cuevas Eduardo 321249050 \\[6pt]
& Peredo López Citlalli Abigail  321161022 \\[6pt]
& Santana de la Rosa Monica Guadalupe 321023663 \\[6pt]
\textbf{Fecha de realización:} & 26/04/2026
\end{array}

</center>

#Cáncer de seno

Divide aleatoriamente la base de datos de cáncer de seno de Wisconsin 3 en un conjunto de entrenamiento con el 70% de los datos y un conjunto de validacióon con el 30% restante. Esta base de datos contiene 699 registros de tumores de seno, de los cuales 458 son benignos y 241 son malignos. Cada registro consta de los siguientes atributos: código muestra grosor Uniformidad del tamaño de la célula Uniformidad de la forma de la célula Adhesión marginal Tamaño de la célula epitelial Núcleos desnudos Cromatina blanda Núcleolos Normales Mitosis de Células Clase Entrena al menos 2 clasificadores de tumores de seno usando distintas distribuciones. Evaluá los clasificadores entrenados tanto con el conjunto de entrenamiento como con el conjunto de validación y discute su desempeño. Existen 16 registros en la base de datos con un atributo no especicado. Investiga estrategias para rellenar los datos faltantes, utiliza las que consideres más adecuadas para este problema y discute el impacto en el desempeño del clasificador
"""

################LIBRERIAS A UTILIZAR
# Importacion de librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, f1_score

# Carga de datos (asumiendo formato estándar de UCI)
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data"
columns = ['id', 'clump_thickness', 'unif_cell_size', 'unif_cell_shape', 'marg_adhesion',
           'single_epith_size', 'bare_nuclei', 'bland_chromatin', 'norm_nucleoli', 'mitoses', 'class']
df = pd.read_csv(url, names=columns)

# Manejo de datos faltantes
# Los datos faltantes vienen como '?' en esta base de datos
df.replace('?', np.nan, inplace=True)
df['bare_nuclei'] = pd.to_numeric(df['bare_nuclei'])
df['bare_nuclei'] = df['bare_nuclei'].fillna(df['bare_nuclei'].median())


# Ajuste de etiquetas: 2 (benigno) -> 0, 4 (maligno) -> 1
df['class'] = df['class'].map({2: 0, 4: 1})

# División 70/30
X = df.drop(['id', 'class'], axis=1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42, stratify=y)

df.head(5)

"""#2. Entrenamiento de Clasificadores
Entrenaremos tres variantes basadas en árboles para comparar la evolución desde un modelo simple hasta uno de ensamble por boosting.
"""

# 1. Árbol de Decisión Simple
dt_model = DecisionTreeClassifier(max_depth=3, random_state=42)
dt_model.fit(X_train, y_train)

# 2. Random Forest (Bagging)
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# 3. XGBoost (Boosting)
xgb_model = XGBClassifier(use_label_encoder=False, eval_metric='logloss', random_state=42)
xgb_model.fit(X_train, y_train)

"""#Árbol de Decisión Simple

1. **max_depth=3 (Profundidad Máxima)**

Este es el parámetro de poda (pruning) más importante para un árbol de decisión simple.
 - Evitar el Overfitting: Si no limitamos la profundidad, el árbol seguirá creciendo hasta que cada hoja sea "pura" (tenga un solo tipo de clase), lo que haría que el modelo memorice los datos de entrenamiento (overfitting) y falle con datos nuevos.
 - Interpretabilidad Académica: Un árbol con profundidad 3 genera un máximo de $2^3 = 8$ nodos hoja. Esto permite que el modelo sea "explicable": un humano puede seguir el flujo de decisiones en una sola imagen y entender por qué el modelo clasificó un tumor como maligno.
 - Punto de Equilibrio: En el dataset de Wisconsin, las reglas suelen ser claras. Una profundidad de 3 suele capturar las relaciones más fuertes (como el tamaño de la célula o el grosor del bulto) sin perderse en el "ruido" de los datos.

 - **Si aumentan max_depth a 10**: El modelo se vuelve una "caja negra" difícil de graficar y explicar, perdiendo la ventaja principal del árbol de decisión frente a modelos más complejos como las redes neuronales.

 2. **random_state=42 (Semilla de Aleatoriedad)**

 Aunque un árbol de decisión parece determinista, hay procesos aleatorios detrás de escenas, especialmente cuando hay empates en la ganancia de información entre dos variables.
 - Repetibilidad: En un entorno académico y de investigación, es vital que si tú ejecutas el código y tus alumnos lo ejecutan después, obtengan exactamente el mismo árbol. Sin una semilla fija, el modelo podría variar ligeramente en cada ejecución.
 - ¿Por qué el número 42?: Es una convención humorística en la comunidad de Ciencia de Datos y Programación, extraída del libro "The Hitchhiker's Guide to the Galaxy", donde el 42 es "la respuesta al sentido de la vida, el universo y todo lo demás". Podría ser cualquier número, pero este es el estándar de facto.

#Random Forest

Es mucho más robusto que un árbol de decisión simple. Mientras que el modelo anterior era un "individuo", aquí estamos creando una "comunidad" de expertos.

Aquí te explico qué hace cada uno en este contexto:

1. n_estimators=100 (El número de árboles)
Este parámetro define que el modelo entrenará 100 árboles de decisión independientes.

- **Sabiduría de las masas:** En lugar de confiar en lo que dice un solo árbol (que puede equivocarse por ruido en los datos), el Random Forest toma la decisión final mediante una votación mayoritaria. Si 85 árboles dicen "maligno" y 15 dicen "benigno", el modelo predice "maligno".

- **Por qué 100?**: Es el valor por defecto estándar en Scikit-Learn porque ofrece un excelente equilibrio. Con 100 árboles, el error suele estabilizarse. Agregar más (por ejemplo, 500 o 1000) puede mejorar ligeramente la precisión, pero el costo computacional aumenta y el beneficio es marginal.

- **Diversidad**: Cada uno de estos 100 árboles no es igual. Gracias a una técnica llamada Bagging, cada árbol ve una submuestra distinta de los datos y un subconjunto distinto de características (como el grosor o la mitosis). Esto garantiza que los errores de un árbol sean compensados por los aciertos de los demás.

2. random_state=42 (La semilla de aleatoriedad)
Al igual que en el modelo anterior, sirve para la reproducibilidad, pero en el Random Forest es aún más crítico debido a la doble aleatoriedad del modelo:

- Aleatoriedad en los datos: Cada uno de los 100 árboles selecciona registros al azar con reemplazo (Bootstrap).

- Aleatoriedad en las características: En cada división (nodo) del árbol, el modelo no elige entre todas las columnas disponibles, sino que elige la mejor entre un grupo pequeño seleccionado al azar.

- Sin el random_state=42, cada vez que corras la celda en Python, los 100 árboles se construirán de forma ligeramente distinta, lo que podría darte una precisión de 96.5% ahora y 96.2% después. Al fijarlo, garantizas que tus resultados y los de tus alumnos sean idénticos y comparables.

Si comparamos los modelos con una analogía médica:

- **Decision Tree (max_depth=3)**: Es como consultar a un médico generalista que tiene un diagrama de flujo simple para decidir.

- **Random Forest (n_estimators=100)**: Es como organizar un panel médico con 100 especialistas. Cada uno analiza el caso desde un ángulo ligeramente diferente y al final votan para dar el diagnóstico más seguro.

- **Dato extra**: En el Random Forest no solemos limitar tanto la profundidad (max_depth) como en el árbol simple, porque la combinación de muchos árboles ya se encarga naturalmente de evitar que el modelo se "sobreajuste" (overfitting).

#Gradient Boosting.

A diferencia de Random Forest, donde los árboles operan en paralelo, en XGBoost los árboles se construyen de forma secuencial: cada nuevo árbol intenta corregir los errores cometidos por los anteriores.

Razón técnica de estos parámetros:

**1. use_label_encoder=False**
Este parámetro es más una cuestión técnica de compatibilidad que de algoritmos.

- El cambio en la API: En versiones anteriores, XGBoost intentaba codificar automáticamente las etiquetas de texto. Sin embargo, la comunidad de Scikit-Learn prefirió que el usuario maneje el preprocesamiento de forma explícita.

- Evitar Warnings: Al ponerlo en False, le indicamos al modelo que nosotros ya nos encargamos de que las etiquetas sean numéricas (en tu caso, cuando mapeamos los datos a 0 y 1). Esto evita que aparezca un mensaje de advertencia durante el entrenamiento.

**2. eval_metric='logloss' (Pérdida Logarítmica)**

Este es el parámetro que define qué tan "mal" lo está haciendo el modelo para que pueda aprender.

- Función de costo: La logloss es la métrica estándar para problemas de clasificación binaria (como Cáncer Benigno vs. Maligno). Penaliza fuertemente las predicciones que son seguras pero incorrectas.

- Optimización: XGBoost usa esta métrica para calcular el "gradiente" (la dirección en la que debe mejorar). Si el modelo predice una probabilidad de 0.9 para cáncer pero el resultado es 0, la logloss será muy alta, obligando al siguiente árbol a enfocarse intensamente en corregir ese tipo de errores.

**3. random_state=42**

Nuevamente, es nuestra semilla de reproducibilidad. Aunque el Boosting es un proceso más dirigido que el Random Forest, XGBoost utiliza aleatoriedad en:

- Subsampling: Puede elegir subconjuntos de datos al azar para cada árbol.

- Column sampling: Puede elegir subconjuntos de características (columnas) para cada división.

- Fijar el 42 permite que, al presentar estos resultados ante el Grupo 7000, todos vean exactamente las mismas métricas de desempeño.

#En resumen:

- **Decision Tree**: Un solo líder decide.Claridad: Es un mapa de reglas que cualquiera puede leer.
- **Random Forest**:	Un comité vota.Estabilidad: Es muy difícil que se equivoque por "ruido".
- **XGBoost**:	Un equipo aprende de sus errores.Potencia: Suele dar la mayor precisión en datos tabulares complejos.

#Visualización de Desempeño
"""

models = ['Decision Tree', 'Random Forest', 'XGBoost']
scores = [accuracy_score(y_test, dt_model.predict(X_test)),
          accuracy_score(y_test, rf_model.predict(X_test)),
          accuracy_score(y_test, xgb_model.predict(X_test))]

plt.figure(figsize=(10, 5))
sns.barplot(x=models, y=scores, palette='viridis')
plt.title('Comparativa de Accuracy entre Modelos')
plt.ylim(0.9, 1.0)
plt.show()

"""Impacto de los datos faltantes: Al ser solo 16 de 699 (aprox. 2%), la imputación por mediana mantiene la integridad estadística sin perder registros valiosos de tumores malignos.

Árbol Simple vs. Ensamble: El árbol simple es altamente interpretable (podemos visualizarlo con plot_tree), pero tiende al overfitting. Random Forest reduce la varianza promediando múltiples árboles, mientras que XGBoost suele dar la mayor precisión al aprender de los errores de los árboles anteriores.

Interpretabilidad Médica: En este problema, atributos como bare_nuclei y uniformity_cell_size suelen aparecer en los niveles superiores del árbol, lo que coincide con los criterios clínicos de diagnóstico.

# Métricas de Clasificación

A continuación se evalúan los tres clasificadores usando **Matriz de Confusión**, **Accuracy (Exactitud)** y **Precisión**.

Dado el contexto médico de este problema, la **Precisión** es especialmente relevante: un falso positivo (diagnosticar maligno a un tumor benigno) genera angustia innecesaria y tratamientos agresivos, mientras que un falso negativo (no detectar un tumor maligno) puede ser fatal. Por ello se reportan ambas métricas para cada modelo.
"""

from sklearn.metrics import accuracy_score, precision_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

modelos_cancer = {
    'Decision Tree':  dt_model,
    'Random Forest':  rf_model,
    'XGBoost':        xgb_model
}

print('--- MÉTRICAS DE CLASIFICACIÓN ---')
print(f"{'Modelo':<20} {'Acc Train':>10} {'Acc Test':>10} {'Precisión Test':>15}")
print('-' * 60)

for nombre, modelo in modelos_cancer.items():
    acc_train = accuracy_score(y_train, modelo.predict(X_train))
    acc_test  = accuracy_score(y_test,  modelo.predict(X_test))
    prec_test = precision_score(y_test, modelo.predict(X_test), zero_division=0)
    print(f"{nombre:<20} {acc_train*100:>9.2f}% {acc_test*100:>9.2f}% {prec_test*100:>14.2f}%")

from sklearn.metrics import ConfusionMatrixDisplay

fig, axs = plt.subplots(1, 3, figsize=(15, 5))

for ax, (nombre, modelo) in zip(axs, modelos_cancer.items()):
    ConfusionMatrixDisplay.from_estimator(
        modelo, X_test, y_test,
        display_labels=['Benigno', 'Maligno'],
        cmap='Blues', colorbar=False, ax=ax
    )
    ax.set_title(f'Matriz de Confusión\n{nombre}')

plt.tight_layout()
plt.show()

"""## Análisis de las Métricas

- **Matriz de Confusión:** Permite identificar exactamente qué tipo de errores comete cada modelo. En diagnóstico médico los **falsos negativos** (tumor maligno clasificado como benigno) son los más peligrosos, pues implican no tratar a un paciente que lo necesita.

- **Accuracy:** El Decision Tree, al tener `max_depth=3`, puede presentar un accuracy de entrenamiento menor que Random Forest y XGBoost, pero con menor riesgo de overfitting. Random Forest y XGBoost generalmente alcanzan accuracies superiores al 96% en este dataset.

- **Precisión:** Mide cuántos de los tumores clasificados como malignos realmente lo son. Un modelo con alta precisión reduce las alarmas falsas, lo cual es importante para evitar tratamientos innecesarios. En este dataset, XGBoost y Random Forest suelen superar al árbol de decisión simple en esta métrica.

#Conclusión

En esta práctica se entrenaron tres clasificadores basados en árboles para detectar tumores de seno benignos y malignos del dataset de Wisconsin: **Árbol de Decisión**, **Random Forest** y **XGBoost**.

Los 16 registros con datos faltantes en `bare_nuclei` se imputaron con la mediana de la columna, estrategia robusta ante valores atípicos. Al representar solo el ~2% del total, el impacto en el desempeño fue mínimo.

En cuanto a los clasificadores, el **Árbol de Decisión** ofrece alta interpretabilidad pero menor capacidad de generalización. El **Random Forest** mejora notablemente al promediar 100 árboles independientes, reduciendo la varianza. **XGBoost** suele obtener la mayor precisión al corregir iterativamente los errores de modelos anteriores.

Desde una perspectiva clínica, la **Precisión** y los **falsos negativos** de la Matriz de Confusión son las métricas más críticas: no detectar un tumor maligno puede tener consecuencias graves para el paciente, por lo que se prefiere un modelo con alta sensibilidad (Recall) aunque sacrifique algo de precisión.

#Referencias Bibliográficas

- Breiman, L. (2001). Random Forests. Machine Learning, 45(1), 5-32.https://link.springer.com/article/10.1023/A:1010933404324

Esta es la fuente primaria y obligatoria para entender el algoritmo de Random Forest y el concepto de Bagging.

- Chen, T., & Guestrin, C. (2016). XGBoost: A Scalable Tree Boosting System. En Proceedings of the 22nd ACM SIGKDD International Conference on Knowledge Discovery and Data Mining (pp. 785–794). ACM. https://dl.acm.org/doi/epdf/10.1145/2939672.2939785

El artículo original que introdujo XGBoost, explicando la regularización y el manejo de datos faltantes que implementamos.

- Pedregosa, F., Varoquaux, G., Gramfort, A., Michel, V., Thirion, B., Grisel, O., Blondel, M., Prettenhofer, P., Weiss, R., Dubourg, V., Vanderplas, J., Passos, A., Cournapeau, D., Brucher, M., Perrot, M., & Duchesnay, E. (2011). Scikit-learn: Machine Learning in Python. Journal of Machine Learning Research, 12, 2825–2830.

Referencia técnica para el uso de DecisionTreeClassifier y RandomForestClassifier dentro del ecosistema de Python.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""