# -*- coding: utf-8 -*-
"""38_UNAM_AI_Actividad_Laboratorio_5_09_Análisis_de_Sentimientos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vodh_maawiXyK9iGM8g4QvyoiaWfwxF9

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Analisis de Sentimientos en Tweets Laboratorio 5.9}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Ayudante de laboratorio:} & Diego Eduardo Peña Villegas \\[6pt]
\textbf{Alumna:} & Santana de la Rosa Monica \\[6pt]
\textbf{Fecha de realización:} & 06/05/2026
\end{array}

</center>

## Contexto:
    
    El año 2020 se vio afectado por el impacto a la sociedad mundial sobre una gripe de alto nivel de contagio así como la causa principal de fallecimientos alrededor del Mundo.
    
    México no ha sido exento del raro virus.
    
    Con el presente Proyecto, el objetivo primordial es desarrollar los algoritmos que ayuden a monitorizar el efecto en los comentarios que en la Red Social de Twitter se emiten, y que ayudé a dar una idea del estado de ánimo de la gente.

<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQUpnfdhCKN1C3OIbNrDdyjctlRsA9t6386WWD8JkUzt_X7JiuH&usqp=CAU" alt="Alt text that describes the graphic" title="Title text" />
"""

!pip install pymongo

# Importacion de librerias
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
#Tienes que descargarte las stopwords primero via nltk.download()
import nltk
from nltk import pos_tag
from nltk.corpus import stopwords
from nltk.corpus import wordnet as wn
from nltk import word_tokenize
from nltk.data import load
from nltk.stem import SnowballStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import sent_tokenize
from nltk.tokenize import word_tokenize
from string import punctuation
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
from collections import defaultdict
from sklearn import model_selection, naive_bayes, svm

import nltk
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')

#Librería MongoDb
#from pymongo import MongoClient
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import nltk
from nltk import pos_tag
from nltk.corpus import stopwords
from string import punctuation
from nltk.stem import WordNetLemmatizer
import seaborn as sns
import time
from datetime import datetime, date, time, timedelta
import calendar

import json
import re
import urllib
import collections

non_words = list(punctuation)
non_words.extend(['¿', '¡'])
non_words.extend(map(str,range(10)))

"""## Preparar los datos

"""

# Importacion del archivo que se nos proporciono agregandole cabeceras que no contiene
names = ['Id', 'tweet', 'polaridad']
dataset = pd.read_csv('train_5.9.txt', sep='\t',names=names)

with open('train_5.9.txt', 'r', encoding='utf-8')  as archivo:
    lista = archivo.read().split('\n')
    print(lista)

dataset.head()

df=pd.DataFrame(dataset)


X = dataset.iloc[:, 1].values
Y = dataset.iloc[:, 2].values

dX=pd.DataFrame(X)
dX.columns = ['tweet']
dX.head(5)

dY=pd.DataFrame(Y)
dY.columns = ['polaridad']
dY.head(5)

dY['polaridad'].unique()

"""## Tokenización, Normalización en minúsculas, StopWords, Stemming y Vectorización"""

df['tweet'] = [entry.lower() for entry in df['tweet']]

import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')

from nltk.tokenize import word_tokenize
# Paso - 1c: Tokenización: en este cada entrada en el corpus se dividirá en un conjunto de palabras
# Paso - 1c: Tokenización
df['tweet'] = df['tweet'].apply(lambda x: word_tokenize(x) if isinstance(x, str) else x)

# Paso - 1d: Eliminar stopwords, no numéricas y aplicar lematización
tag_map = defaultdict(lambda : wn.NOUN)
tag_map['J'] = wn.ADJ
tag_map['V'] = wn.VERB
tag_map['R'] = wn.ADV

for index, entry in enumerate(df['tweet']):
    Final_words = []
    word_Lemmatized = WordNetLemmatizer()
    # Etiquetar POS
    for word, tag in pos_tag(entry):
        if word not in stopwords.words('spanish') and word.isalpha():
            word_Final = word_Lemmatized.lemmatize(word, tag_map[tag[0]])
            Final_words.append(word_Final)
    df.loc[index, 'tweet_final'] = str(Final_words)

print(df.loc[index, 'tweet_final'])

df.head(5)

"""## Datos de Entrenamiento y Pruebas"""

Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(df['tweet_final'],df['polaridad'],test_size=0.3)

Train_Y.head(5)

Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

print(Train_Y)

df.head()

Tfidf_vect = TfidfVectorizer(max_features=5000)
Tfidf_vect.fit(df['tweet_final'])
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

"""## Identificación de Polaridad con  Algoritmos de Aprendizaje Supervisado"""

# Clasificador - Algoritmo - Naive Bayes
# Se ajusta el conjunto de datos de entrenamiento en el clasificador
Naive = naive_bayes.MultinomialNB()
Naive.fit(Train_X_Tfidf,Train_Y)
# Predecir las etiquetas en el conjunto de datos de validación
predictions_NB = Naive.predict(Test_X_Tfidf)
# Usando la función de precision_score para obtener la precisión
print("Naive Bayes Accuracy Score -> ",accuracy_score(predictions_NB, Test_Y)*100)

# Clasificador - Algoritmo - SVM
# Se ajusta el conjunto de datos de entrenamiento en el clasificador
SVM = svm.SVC(C=1.20, kernel='linear', degree=3, gamma='auto',   max_iter=1000,  tol=0.0001)
SVM.fit(Train_X_Tfidf,Train_Y)
# predecir las etiquetas en el conjunto de datos de validación
predictions_SVM = SVM.predict(Test_X_Tfidf)
# Usando la función precision_score para obtener la precisión
print("SVM Accuracy Score -> ",accuracy_score(predictions_SVM, Test_Y)*100)

print(SVM)

# Prediccion del conjunto de prueba de acuerdo al 30% para los entrenamientos 120 registros
y_pred = SVM.predict(Test_X_Tfidf)

print(Test_Y)

print(y_pred)

# Matriz de confusion
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Test_Y, y_pred, labels=[0, 1, 2])
cm

import seaborn as sns
import matplotlib.pyplot as plt

ax= plt.subplot()
sns.heatmap(cm, annot=True, ax = ax); #annot=True to annotate cells

# Etiquetas, Título and medidas
ax.set_xlabel('Etiquetas Predictivas');ax.set_ylabel('Etiquetas Verdaderas');
ax.set_title('MATRIZ DE CONFUSIÓN');
ax.xaxis.set_ticklabels(['Positivos', 'Neutros','Negativos']); ax.yaxis.set_ticklabels(['Positivos', 'Neutros','Negativos']);

"""# WordCount"""

names = ['Id', 'tweet', 'polaridad']
palabras = pd.read_csv('train_5.9.txt', sep='\t',names=names)

palabras['tweet2'] = palabras.tweet.str.strip().str.split('[\W_]+')

rows = list()
for row in palabras[['tweet2']].iterrows():
    r = row[1]
    for word in r.tweet2:
        rows.append((word))

tweet2 = pd.DataFrame(rows, columns=['tweet2'])
tweet2.head()

tweet2 = tweet2[tweet2.tweet2.str.len() > 0]
tweet2['tweet2'] = tweet2.tweet2.str.lower()
tweet2.head()

counts = tweet2\
    .tweet2.value_counts()\
    .to_frame()\
    .rename(columns={'tweet2':'n_w'})
counts.head(15)

stopwords = stopwords.words('spanish')

for a_stopword in stopwords:
    if a_stopword in counts.index:
        counts = counts.drop(a_stopword)

counts.head(20)

top_500 = counts.head(500)

top_20 = counts.head(20)
top_20

top_20['palabras'] = counts.head(20)
top_20

# --- 2) Preparar top20 correctamente
top20 = counts.head(20).reset_index()         # index -> columna
top20.columns = ['word', 'n_w']               # renombrar columnas
# en caso de que alguna cosa no sea numérica:
top20['n_w'] = top20['n_w'].astype(int)

# Ordenar de menor a mayor para luego invertir el eje y y tener el mayor arriba
top20 = top20.sort_values('n_w', ascending=False).reset_index(drop=True)

# Verifica rápidamente (opcional)
print(top20.head())   # debe mostrar 'word' y 'n_w'

# --- 3) Plot con matplotlib (control total, evita warnings de seaborn)
fig, ax = plt.subplots(figsize=(14,10))

y_positions = np.arange(len(top20))

# paleta usando colormap (evitamos tonos muy claros para que se vean bien)
colors = plt.cm.YlOrBr(np.linspace(0.15, 0.85, len(top20)))

ax.barh(y_positions, top20['n_w'], color=colors, edgecolor='none')

# Etiquetas de palabras en eje Y
ax.set_yticks(y_positions)
ax.set_yticklabels(top20['word'], fontsize=12)

# Poner la palabra más frecuente arriba
ax.invert_yaxis()

# Etiquetas y título
ax.set_xlabel('Times appearing', fontsize=14)
ax.set_title('Top 20 words appearing in songs', fontsize=18)

# Números al final de cada barra
max_n = top20['n_w'].max()
for i, v in enumerate(top20['n_w']):
    ax.text(v + max_n*0.01, i, str(v), va='center', fontsize=11)

plt.tight_layout()
plt.savefig('palabras_populares.jpg', dpi=150)
plt.show()

top_five_words = counts.head(5).index
top_five_words

!pip install wordcloud
#conda install -c conda-forge wordcloud

import re
from PIL import Image
from wordcloud import WordCloud
from collections import Counter

comment_words = ' '
for val in counts.index:
    # typecaste each val to string
    val = str(val)

    # split the value
    tokens = val.split()

    # Converts each token into lowercase
    for i in range(len(tokens)):
        tokens[i] = tokens[i].lower()

    for words in tokens:
        comment_words = comment_words + words + ' '

trump_mask = np.array(Image.open("bajo_5.9.jpg"))

wordcloud = WordCloud(width = 800, height = 800,
                background_color ='white',
                stopwords = stopwords,
                mask=trump_mask,
                min_font_size = 10).generate(comment_words)
# plot the WordCloud image
plt.figure(figsize = (8, 8), facecolor = None)
plt.imshow(wordcloud)
plt.axis("off")
plt.tight_layout(pad = 0)

plt.show()

"""### Conclusión

En esta práctica se aplicaron técnicas de NLP y modelos como Naive Bayes y SVM para clasificar sentimientos, obteniendo un rendimiento moderado (mejor con SVM). Se observaron dificultades especialmente en la clase neutral.

Comparado con herramientas como Text2Data, los resultados son inferiores, lo que muestra que los modelos modernos (como Transformers) logran mayor precisión y mejor comprensión del contexto.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""