# -*- coding: utf-8 -*-
"""39_UNAM_AI_Actividad_Laboratorio_5_10_REGEX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KFtYkDI4IyxcpbuvAbzPhTUdRBkpHxt

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 5.10}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Ayudante de laboratorio:} & Diego Eduardo Peña Villegas \\[6pt]
\textbf{Alumna:} & Santana de la Rosa Monica \\[6pt]
\textbf{Fecha de realización:} & 06/05/2026
\end{array}

</center>

Expresiones Regulares (Regex): Una Guía Básica

Las expresiones regulares, comúnmente conocidas como regex o regexp, son patrones de búsqueda utilizados para realizar búsquedas y manipulación de texto de manera eficiente. Estas secuencias de caracteres permiten especificar un conjunto de reglas que definen un patrón de coincidencia dentro de una cadena de texto. Son una herramienta poderosa y versátil utilizada en programación, procesamiento de texto y manipulación de datos.

Principales Reglas de Uso:

- Símbolos Literales: Los caracteres simples en una expresión regular coinciden literalmente con ellos mismos en el texto. Por ejemplo, la expresión regular gato buscará la palabra "gato" en un texto.

- Cuantificadores: Los cuantificadores especifican la cantidad de ocurrencias de un elemento. Por ejemplo, a{3} coincidirá con exactamente tres letras "a". Además, a+ coincidirá con una o más letras "a".

- Caracteres Especiales: Algunos caracteres tienen significados especiales en expresiones regulares. Por ejemplo, el punto (.) coincide con cualquier carácter, y el asterisco (*) coincide con cero o más ocurrencias del elemento anterior.

- Conjuntos de Caracteres: Se pueden definir conjuntos de caracteres utilizando corchetes ([]). Por ejemplo, [aeiou] coincidirá con cualquier vocal.

- Negación de Conjuntos: Un acento circunflejo (^) dentro de corchetes negará el conjunto. Por ejemplo, [^0-9] coincidirá con cualquier carácter que no sea un dígito.

- Anclajes: Los anclajes indican la posición en la que debe ocurrir un patrón. Por ejemplo, ^ representa el inicio de una línea, y $ representa el final de una línea.

- Grupos y Captura: Los paréntesis (()) se utilizan para agrupar elementos y formar subpatrones. Además, permiten la captura de la parte coincidente para su posterior uso.

- Caracteres de Escape: Algunos caracteres tienen significados especiales en expresiones regulares. Si deseas buscar estos caracteres literalmente, debes escaparlos con una barra invertida (\).


Estas reglas son solo el punto de partida para entender las expresiones regulares. A medida que te familiarices con ellas, descubrirás su potencial para realizar búsquedas y manipulaciones de texto de manera eficiente y precisa. Aprender a utilizar expresiones regulares es una habilidad valiosa que mejora la capacidad de procesamiento y manipulación de datos en el ámbito de la programación y más allá.

https://regexr.com/

#Ejercicios
"""

import re

# Ejercicio 1
# Encuentra todas las coincidencias de "gato" en el texto.
texto = "El gato está en el tejado. El gato es un animal goméstico."
resultado = re.findall(r"gato", texto)
print("Ejercicio 1:", resultado)

# Ejercicio 2
# Encuentra todas las palabras que comienzan con "g" en el texto.
resultado = re.findall(r'\bg\w*', texto)
print("Ejercicio 2:", resultado)

# Ejercicio 3
# Reemplaza todas las direcciones de correo electrónico en el texto con "email@dominio.com".
texto_con_correos = "Mi dirección de correo es user1@example.com y user2@gmail.com"
resultado = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', 'email@dominio.com', texto_con_correos)
print("Ejercicio 50:", resultado)

# Ejercicio 4
# Encuentra todas las palabras que terminan con "o" en el texto.
texto = "El gato está en el tejado. El perro está en el suelo."
resultado = re.findall(r'\b\w*o\b', texto)
print("Ejercicio 4:", resultado)

# Ejercicio 5
# Encuentra todas las coincidencias de números (dígitos) en el texto.
texto = "La casa tiene 3 habitaciones y el precio es $200,000."
resultado = re.findall(r'\d+', texto)
print("Ejercicio 5:", resultado)

# Ejercicio 6
# Encuentra todas las líneas que comienzan con "Hola".
texto = "Hola, ¿cómo estás?\nHola, me llamo Juan.\nAdiós por ahora."
resultado = re.findall(r'^Hola.*', texto, flags=re.MULTILINE)
print("Ejercicio 6:", resultado)

# Ejercicio 7
# Encuentra todas las palabras que tienen al menos tres vocales en el texto.
texto = "Python es un lenguaje de programación poderoso."
resultado = re.findall(r'\b(?:[aeiouAEIOU][^aeiouAEIOU]*){3,}\b', texto)
print("Ejercicio 7:", resultado)

"""**Ejercicio 7**

El patrón completo es `\b(?:[aeiouAEIOU][^aeiouAEIOU]*){3,}\b`. Para entenderlo hay que descomponerlo en partes.

Los `\b` al inicio y al final son anclajes de límite de palabra. Le dicen al motor que la coincidencia debe comenzar y terminar en el borde entre un carácter de palabra y uno que no lo es, como un espacio o un signo de puntuación.

El núcleo del patrón es el grupo `(?:[aeiouAEIOU][^aeiouAEIOU]*)`. El `?:` indica que es un grupo no capturante, es decir, agrupa la expresión para aplicarle un cuantificador pero no guarda lo que encuentra. Dentro del grupo, `[aeiouAEIOU]` es una clase de caracteres que coincide con exactamente una vocal, ya sea mayúscula o minúscula. Inmediatamente después, `[^aeiouAEIOU]*` es otra clase de caracteres pero negada con `^`, lo que significa que coincide con cualquier carácter que no sea una vocal. El `*` permite que aparezca cero o más veces. Entonces el grupo completo representa una vocal seguida de cualquier cantidad de no-vocales, que en una palabra normal serían consonantes.

El cuantificador `{3,}` aplicado al grupo le exige que ese patrón ocurra al menos 3 veces seguidas, lo que equivale a pedir que la palabra tenga al menos 3 vocales.

El problema está en que `[^aeiouAEIOU]*` no distingue entre consonantes y espacios. Ambos son "no-vocales". Entonces cuando el motor termina de procesar una palabra y encuentra un espacio, lo consume como parte del patrón porque el espacio satisface `[^aeiouAEIOU]*`, y sigue buscando la siguiente vocal en la palabra siguiente. Así cruza todas las palabras del texto sin detenerse y devuelve `'es un lenguaje de programación poderoso'` como una sola coincidencia gigante en lugar de palabras individuales.
"""

# Ejercicio 8
# Extrae el nombre de usuario y dominio de las direcciones de correo electrónico.
texto = "Mis correos son user1@example.com y user2@gmail.com"
resultado = re.findall(r'(\w+)@(\w+\.\w+)', texto)
print("Ejercicio 8:", resultado)

# Ejercicio 9
# Encuentra todas las palabras que contienen al menos dos letras "a".
texto = "La manzana es roja y el plátano es amarillo."
resultado = re.findall(r'\b(?:[^a]*a[^a]*){2,}\b', texto)
print("Ejercicio 9:", resultado)

# Ejercicio 10
# Encuentra todas las fechas en formato dd/mm/aaaa en el texto.
texto = "Hoy es 05/12/2023 y mañana será 06/12/2023."
resultado = re.findall(r'\b\d{2}/\d{2}/\d{4}\b', texto)
print("Ejercicio 10:", resultado)

# Ejercicio 11
# Encuentra todas las palabras que comienzan y terminan con la misma letra en el texto.
texto = "oso casa pera elefante nivel"
resultado = re.findall(r'\b(\w)\w*\1\b', texto)
print("Ejercicio 11:", resultado)

"""**Ejercicio 11**

El patrón es `\b(\w)\w*\1\b` y es un ejemplo clásico del uso de backreferences.

El `\b` inicial ancla el inicio en un límite de palabra. Luego `(\w)` es un grupo capturante, marcado por los paréntesis sin `?:`. Captura exactamente un carácter de palabra, que puede ser una letra o un dígito, y lo guarda en la memoria del motor bajo el nombre de grupo 1. Esta es la primera letra de la palabra.

A continuación `\w*` coincide con cero o más caracteres de palabra. Esto cubre todas las letras intermedias de la palabra. El `*` permite que sea cero, lo que en teoría permitiría palabras de una sola letra, aunque en ese caso no habría letras intermedias y la primera y última serían la misma.

La parte más interesante es `\1`. Esto es una backreference al grupo 1, es decir, le dice al motor que en esa posición debe aparecer exactamente el mismo texto que se capturó entre los primeros paréntesis. Si la primera letra fue `o`, entonces `\1` exige que la última letra también sea `o`. Si fue `e`, exige `e`. Es como si el patrón se reescribiera dinámicamente según lo que encontró al principio.

Aplicado al texto `"oso casa pera elefante nivel"`, el motor evalúa cada palabra. En `oso` captura `o`, recorre `s` con `\w*`, y verifica que la última letra sea `o`, lo cual se cumple. En `elefante` captura `e`, recorre `lefant` con `\w*`, y verifica que termine en `e`, lo cual también se cumple. Las demás palabras no pasan la verificación.

Sin embargo el resultado impreso es `['o', 'e']` en lugar de `['oso', 'elefante']`. Esto ocurre por un comportamiento específico de `re.findall()`: cuando el patrón contiene grupos de captura, la función no devuelve las coincidencias completas sino únicamente el contenido de los grupos. Como el único grupo capturante es `(\w)`, que guarda solo la primera letra, eso es exactamente lo que regresa. La coincidencia completa existe internamente en el motor pero `findall` la descarta. Para recuperar la palabra entera habría que envolver todo el patrón en un grupo adicional o usar `re.finditer()` y acceder a `match.group(0)`.
"""

# Ejercicio 12
# Encuentra todas las oraciones que terminan con un signo de exclamación en el texto.
texto = "¡Hola! ¿Cómo estás? ¡Esto es emocionante!"
resultado = re.findall(r'.*!\b', texto)
print("Ejercicio 12:", resultado)

# Ejercicio 13
# Reemplaza todas las ocurrencias de "Python" con "JavaScript" en el texto.
texto = "Python es un lenguaje poderoso. Me encanta programar en Python."
resultado = re.sub(r'Python', 'JavaScript', texto)
print("Ejercicio 13:", resultado)

# Ejercicio 14
# Encuentra todas las palabras que tienen al menos una letra seguida por dos números.
texto = "abc123 x1y2z3 45a67"
resultado = re.findall(r'\b\w*[a-zA-Z]\d{2}\w*\b', texto)
print("Ejercicio 14:", resultado)

# Ejercicio 15
# Encuentra todas las líneas que contienen la palabra "información" (sin importar mayúsculas o minúsculas).
texto = "La información es clave.\nRecuerda revisar la Información importante."
resultado = re.findall(r'(?i)información', texto)
print("Ejercicio 15:", resultado)

# Ejercicio 16
# Encuentra todas las palabras que empiezan con "b" pero no terminan con "o".
texto = "barco bolsa libro plato bote"
resultado = re.findall(r'\bb[^o\s]*\b', texto)
print("Ejercicio 16:", resultado)

# Ejercicio 17
# Encuentra todas las palabras que tienen al menos una consonante repetida (como "cc" en "coco").
texto = "coco pera manzana barco"
resultado = re.findall(r'\b\w*([bcdfghjklmnpqrstvwxyz])\1\w*\b', texto)
print("Ejercicio 17:", resultado)

# Ejercicio 18
# Encuentra todas las palabras que contienen al menos una vocal y al menos un número.
texto = "apple23 45orange 6pear"
resultado = re.findall(r'\b\w*[aeiou]\d+\w*\b', texto)
print("Ejercicio 18:", resultado)

# Ejercicio 19
# Encuentra todas las líneas que comienzan con una letra mayúscula en el texto.
texto = "Hola Mundo.\nPython es genial.\nel cielo es azul."
resultado = re.findall(r'^[A-Z].*', texto, flags=re.MULTILINE)
print("Ejercicio 19:", resultado)



# Ejercicio 20
# Encuentra todas las palabras que contienen solo letras mayúsculas.
texto = "Python ES un Lenguaje de Programación."
resultado = re.findall(r'\b[A-Z]+\b', texto)
print("Ejercicio 20:", resultado)

"""#Desafío 1:
Objetivo: Encuentra todas las direcciones de correo electrónico en el siguiente texto.

Contacta con nosotros en support@example.com o info@company.org para obtener ayuda.
Recuerda enviar tus comentarios a feedback@company.org. ¡Gracias!

Resultado esperado:

['support@example.com', 'info@company.org', 'feedback@company.org']
"""

import re

texto = ("Contacta con nosotros en support@example.com o "
         "info@company.org para obtener ayuda. Recuerda "
         "enviar tus comentarios a feedback@company.org. ¡Gracias!")

resultado = re.findall(
    r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b',
    texto
)
print("Desafío 1:", resultado)

"""#Desafío 2:

Objetivo: Encuentra todas las palabras que comienzan con "a" y terminan con "o" en el siguiente texto.

El árbol es alto y tiene un fruto. El auto rojo está aparcado cerca.
Algunos animales, como el león y el mono, viven en el zoológico.
"""

import re

texto = ("El árbol es alto y tiene un fruto. El auto rojo "
         "está aparcado cerca. Algunos animales, como el "
         "león y el mono, viven en el zoológico.")

resultado = re.findall(r'\b[aáAÁ]\w*o\b', texto)
print("Desafío 2:", resultado)

"""Resultado Esperado:

['árbol', 'auto']

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""