# -*- coding: utf-8 -*-
"""43_UNAM_AI_Actividad_Laboratorio_5_14_operadores_geometricos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vY2TBx0qmBBo5juGf8RQXprhP1nTuXjO

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 5.14}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Alumna:} & Santana de la Rosa Monica \\[6pt]
\textbf{Fecha de realización:} & 13/05/2026
\end{array}

</center>

**UNAM y la creadora del presente notebook, no guarda relación alguna con las marcas mencionadas como ejemplo. Las marcas son propiedad de sus titulares conforme a la legislación aplicable, se utilizan con fines académicos y didácticos, por lo que no existen fines de lucro, relación publicitaria o de patrocinio.

---
"""

!pip install opencv-python

import matplotlib.pyplot as plt
import cv2 as cv
import numpy as np

img = cv.imread('/content/tay_5.14.jpg')
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
plt.imshow(img, cmap='gray')

"""#Rotación"""

centro = (img.shape[1]//2,img.shape[0]//2)
matriz_rot = cv.getRotationMatrix2D(centro,-45,1)
img_rot = cv.warpAffine(img, matriz_rot,(img.shape[1],img.shape[0]))
plt.imshow(img_rot, cmap='gray')

from numpy.core.multiarray import min_scalar_type
import numpy as np

esq_orig = [(0,0,1),(400,0,1),(0,200,1),(400,200,1)]
esq_nueva = [np.matmul(matriz_rot,pt) for pt in esq_orig]

min_x=np.min([pt[0] for pt in esq_nueva])
max_x=np.max([pt[0] for pt in esq_nueva])

min_y=np.min([pt[1] for pt in esq_nueva])
max_y=np.max([pt[1] for pt in esq_nueva])

dim_nueva=(int(max_y-min_y),int(max_x-min_x) )

print('Las dimensiones de la imagen nueva son : ', dim_nueva)

centro_nuevo = (dim_nueva[0]//2, dim_nueva[1]//2)
tras_Centro = (centro_nuevo[0] - centro[0], centro_nuevo[1] - centro[1])

matriz_rot[0][2] += tras_Centro[0]
matriz_rot[1][2] += tras_Centro[1]

img_rot2 = cv.warpAffine(img, matriz_rot,dim_nueva)
plt.imshow(img_rot2,cmap = 'gray')

"""#Traslación"""

alto, ancho = img.shape[:2]
tx, ty = ancho/2, alto/2
matriz_tras = np.array([[1,0,tx],[0,1,ty]], dtype=np.float32)
img_tras =  cv.warpAffine(src = img, M=matriz_tras, dsize=(ancho, alto))
plt.imshow(img_tras, cmap='gray')

ancho

"""#Escalamiento"""

ancho_red = 1200
alto_red = 3000
puntos_red = (ancho_red, alto_red)
img_red = cv.resize(img, puntos_red, interpolation=cv.INTER_LINEAR)
plt.imshow(img_red, cmap = 'gray')

h,w,c =img.shape
print("Altura y ancho de la imagen original", h, "x",w)

esca_red_x = 3
esca_red_y = 3

img_red = cv.resize(img, None, fx=esca_red_x, fy=esca_red_y, interpolation =cv.INTER_AREA)
plt.imshow (img_red, cmap='gray')
h,w,c = img_red.shape
print("Altura y ancho de la imagen modificada", h, "x",w)

"""#Conclusión

En conclusión, esta práctica me ayudó a comprender cómo funcionan los operadores geométricos en el procesamiento digital de imágenes, aplicando transformaciones como rotación, traslación y escalamiento con OpenCV. Considero que trabajar con imágenes de Taylor Swift hizo la actividad más interesante y dinámica, ya que pude observar de manera más clara los cambios realizados en cada transformación. Además, entendí la importancia de estas herramientas dentro de la visión por computadora y la Inteligencia Artificial.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""