# -*- coding: utf-8 -*-
"""46_UNAM_AI_Actividad_Laboratorio_5_17_SIFT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tx-nWMNyXm3vWCTs3p69B7JUTBllYz3N

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 5.17}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Alumna:} & Santana de la Rosa Monica \\[6pt]
\textbf{Fecha de realización:} & 13/05/2026
\end{array}

</center>
"""

!pip install opencv-python

"""**Detección del punto de interés**

En procesamiento de imágenes, un atributo o característica de imagen es un fragmento de información sobre el contenido de esta. Por lo general esta información es sobre si una determinada región de la imagen contiene ciertas propiedades. Los atributos o características pueden ser estructuras específicas como puntos, bordes, esquinas u objetos en particular, así como también pueden ser el resultado de una operación hecha sobre una vecindad de puntos.

**La transformación de características invariantes de escala (SIFT)** es un algoritmo de detección en visión computacional. Permite identificar características locales dentro de una imagen conocidas como puntos de interés. Los puntos de interés son invariantes a la escala y rotación. La principal ventaja de esta transformación es que las características obtenidas no se ven afectadas por el tamaño de la imagen o su orientación, lo que significa que independientemente de si la imagen es girada o modificada en escala, se encontrarán los mismos puntos de interés.

El proceso para la identificación de estos puntos de interés se divide en cuatro etapas (Lowe, 2004):

-  **Construcción del espacio de escala**. Se identifican la ubicación y escalas de las características que se pueden reconocer de forma repetida desde diferentes perspectivas en el mismo objeto o escena. Se asegura que las características sean independientes a la escala.
-  **Localización de puntos interés.** Ajusta un modelo para determinar la ubicación y escalas de las características seleccionando puntos clave en función de una medida de estabilidad.
-  **Asignación de la orientación.** Se asegura de que los puntos de interés sean invariantes a la rotación. Se calculan las mejores orientaciones para cada región que contiene puntos de interés.
-  **Descriptor del punto de interés.** Asigna una “huella digital” única a cada punto de interés. Se utilizan degradados de imagen en la escala y rotación seleccionada para describir cada región que contiene puntos de interés.
"""

import cv2 as cv
import matplotlib.pyplot as plt

img1 = cv.imread('estatua_5.17.jpg')
gray1  = cv.cvtColor (img1, cv.COLOR_BGR2GRAY)

#Puntos de intes
sift =cv.SIFT_create()

kp1, descriptor1 =sift.detectAndCompute(img1, None)
img1kp = cv.drawKeypoints(gray1, kp1, img1,
                          flags = cv.DrawMatchesFlags_DRAW_RICH_KEYPOINTS)
plt.figure(figsize = (6,6))

plt.imshow(img1kp)

img1 = cv.imread('estatua_5.17.jpg')
img1  = cv.cvtColor (img1, cv.COLOR_BGR2GRAY)
img2 = cv.imread('estatua1_5.17.jpg')
img2  = cv.cvtColor (img2, cv.COLOR_BGR2GRAY)
figure , ax = plt.subplots(1,2, figsize = (16,8))

ax[0].imshow(img1, cmap = 'gray')
ax[1].imshow(img2, cmap = 'gray')

#SIFT
sift = cv.SIFT_create()

kp1, descriptor1 = sift.detectAndCompute(img1, None)
kp2, descriptor2 = sift.detectAndCompute(img2, None)

#Coincidencias de caracteristicas
bf = cv.BFMatcher(cv.NORM_L1, crossCheck = True)

match1 = bf.match(descriptor1,descriptor2)
match1 = sorted(match1, key = lambda x: x.distance)

img3 = cv.drawMatches(img1, kp1, img2, kp2, match1[:500], img2, flags = 2)
plt.figure(figsize=(9,9))
plt.imshow(img3)

"""#Conclusión

En conclusión, esta práctica me permitió comprender cómo funciona el algoritmo SIFT para la detección de puntos de interés y coincidencias entre imágenes. Aprendí que SIFT puede identificar características importantes que permanecen aunque la imagen cambie de tamaño o rotación, lo que resulta muy útil en visión por computadora. Además, pude observar cómo se detectan y comparan puntos clave entre diferentes imágenes, entendiendo mejor la importancia de los descriptores y las coincidencias de características en aplicaciones de Inteligencia Artificial y procesamiento digital de imágenes.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""