# -*- coding: utf-8 -*-
"""48_UNAM_AI_Actividad_Laboratorio_5_19_haarcascades_detect_multiScale.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OAXEgpPd-JW8rbBfcOmUF5fRIn_3Lf9v

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 5.19}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Alumna:} & Santana de la Rosa Monica \\[6pt]
\textbf{Fecha de realización:} & 13/05/2026
\end{array}

</center>
"""

# Se instala opencv-python para usar las librerias correspondientes y necesarias.
!pip install opencv-python

# Se importan las librerías de para capturar, detectar y procesar los rostros de las personas
import cv2
import numpy as np
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

# Se carga la imagen con la que se desarrollara la segunda fase en escalas de grises procesando la imagen y realizando la comparación con su respectiva ecualización de histograma.
img = cv2.imread('tay_5.19.jpg', cv2.IMREAD_GRAYSCALE)
width, height = img.shape

cv2_imshow (img)
x = np.linspace(0,255, num=256, dtype = np.uint8)
y = np.zeros(256)

for w in range (width):
	for h in range (height):
		v=img[w,h]
		y[v] = y[v]+1;
plt.bar(x,y)
plt.show()

# En esta parte del código se implementa el detector de rostros, empezando con el guardado en la función faceClassif del despliegue del xml de un clasificador de rostros previamente entrenado con Haar Cascade de OpenCV por parte de GitHub,
# mismo donde se llama a la función "detectMultiScale" introduciendo el factor de escalado de la imagen a un valor de escala original (1.1), ajustando los parámetros de minNeighbors con la frecuencia de reconocimiento de posible rostro para
# ajustar el promedio de rostros vecinos o cercanos, el mínimo y el máximo escalado de tamaño detectado del recuadro identificador de rostros en la imagen  con "minSize" y "maxSize" respectivamente, ajustando las dimensiones de los recuadros.
import cv2
import numpy as np

faceClassif =  cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

faces = faceClassif.detectMultiScale(img,
	scaleFactor=1.1,
	minNeighbors=5,
	minSize=(30,30),
	maxSize=(200,200))

for (x,y,w,h) in faces:
	cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)

cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Finalmente se usa la variable reservada con haar cascade para la detección de rostros de la líne anterior, utilizando el factor de escala original y el tamaño ajustado para los rostros de la imagen, implementando el código de filtro gaussiano,
# con un bucle sobre todas las caras detectadas en la imagen, se aplica el filtro gaussiano de desenfoque o "blur"  al rectángulo de la cara, agregando una cara borrosa en la imagen original para obtener y mostarel resultado de la imagen final.
faces = faceClassif.detectMultiScale(img, 1.1, 5)
print("Face detected in the image:", len(faces))


for (x, y, w, h) in faces:
   roi = img[y:y+h, x:x+w]


   roi = cv2.GaussianBlur(roi, (15, 15), 30)


   img[y:y+roi.shape[0], x:x+roi.shape[1]] = roi


cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()

"""#Conclusión

En conclusión, esta práctica me permitió comprender cómo funciona la detección de rostros utilizando clasificadores Haar Cascade y la función detectMultiScale de OpenCV. Aprendí a identificar rostros en imágenes, ajustar parámetros de detección y aplicar filtros como GaussianBlur para modificar regiones específicas de la imagen. Además, trabajar con imágenes de Taylor Swift hizo la actividad más interesante y me ayudó a observar claramente cómo se detectan y procesan los rostros dentro del área de visión por computadora e Inteligencia Artificial.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""