# -*- coding: utf-8 -*-
"""51_UNAM_AI_Actividad_Laboratorio_5_23_Text_To_Speech.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k2hREn6ytPPYXgbHWwp11nbmDgcbCLwx

<center>

$\Huge \textbf{Universidad Nacional Autónoma de México}$  
$\Huge \textbf{Facultad de Ciencias}$  
<p align="center">
  <img src="https://www.icat.unam.mx/wp-content/uploads/2021/11/Copia-de-LogoUNAM.-Azul.-Fondo-transparente.png" alt="UNAM" width="200"/>
</p>

<hr style="height:3px; background-color:#0B6E4F; border:none;"/>


$\LARGE \textbf{Inteligencia Artificial}$  

$\Large \textit{Laboratorio 5.22}$  


\begin{array}{rl}
\textbf{Docente:} & Dra. Jessica Sarahi Méndez Rincón \\[6pt]
\textbf{Alumna:} & Santana de la Rosa Monica \\[6pt]
\textbf{Fecha de realización:} & 13/05/2026
\end{array}

</center>



---

**UNAM y la creadora del presente notebook, no guarda relación alguna con las marcas mencionadas como ejemplo. Las marcas son propiedad de sus titulares conforme a la legislación aplicable, se utilizan con fines académicos y didácticos, por lo que no existen fines de lucro, relación publicitaria o de patrocinio.

---
"""

!pip install pyttsx3

!apt-get install -y espeak espeak-ng libespeak-dev alsa-utils

!pip install gTTS

from gtts import gTTS
from IPython.display import Audio

# 1. Definir el texto
texto = (
    "Cada que Juan Carlos Iracheta terminaba de dar el reporte del clima, "
    "para despedirse recitaba la frase: Espero que tenga usted un día de intenso calor."
)

# 2. Crear el objeto TTS especificando el idioma en español ('es')
# Puedes usar 'es-us' para acento latino o 'es' para estándar
tts = gTTS(text=texto, lang='es', slow=False)

# 3. Guardar el resultado en un archivo de audio temporal
archivo_audio = 'iracheta_clima.mp3'
tts.save(archivo_audio)

# 4. Mostrar el reproductor de audio nativo en Google Colab
Audio(archivo_audio, autoplay=False)

"""# Ejercicio 1: El Traductor y Políglota (Manejo de múltiples idiomas)

gTTS soporta decenas de idiomas. En este ejercicio, configuraremos un diccionario con una misma frase traducida a diferentes idiomas (español, inglés, francés y japonés) y generaremos los audios en un ciclo para comparar cómo suenan las pronunciaciones nativas de Google.
"""

from gtts import gTTS
from IPython.display import Audio, display

# 1. Definimos un diccionario con el texto y su respectivo código de idioma
frases_multilingues = {
    "Español": {"texto": "Bienvenidos al fascinante mundo de la inteligencia artificial.", "lang": "es"},
    "Inglés": {"texto": "Welcome to the fascinating world of artificial intelligence.", "lang": "en"},
    "Francés": {"texto": "Bienvenue dans le monde fascinante de l'intelligence artificielle.", "lang": "fr"},
    "Japonés": {"texto": "人工知能の魅惑的な世界へようこそ。", "lang": "ja"}
}

# 2. Iteramos sobre el diccionario para generar y mostrar cada audio
print("--- Generando reproducciones multilingües ---")
for idioma, info in frases_multilingues.items():
    # Crear el objeto TTS para el idioma específico
    tts = gTTS(text=info["texto"], lang=info["lang"], slow=False)

    # Nombre de archivo único por idioma
    nombre_archivo = f"audio_{info['lang']}.mp3"
    tts.save(nombre_archivo)

    # Mostramos una etiqueta y el reproductor en la celda
    print(f"\n📢 Idioma: {idioma} ({info['texto']})")
    display(Audio(nombre_archivo, autoplay=False))

"""# Ejercicio 2: El Lector de diálogos interactivos (Simulación de una conversación)

En este ejercicio vamos a simular un diálogo interactivo entre dos personajes utilizando variables para automatizar la lectura de un guion. Además, utilizaremos el parámetro slow=True en uno de los personajes para simular que habla de forma más pausada o reflexiva.
"""

from gtts import gTTS
from IPython.display import Audio, display
import time

# 1. Definimos el guion de la conversación
# Cada elemento es una tupla: (Personaje, Texto, Velocidad_Lenta)
guion = [
    ("Profesor", "Hola a todos. Hoy analizaremos el comportamiento de los algoritmos estocásticos.", False),
    ("Estudiante", "Profesor, ¿podríamos usar un modelo de Markov para predecir el clima como Iracheta?", False),
    ("Profesor", "Excelente pregunta. De hecho, un Modelo Oculto de Markov es perfecto para eso.", True)
    # El profesor habla lento en su última intervención para enfatizar la explicación.
]

# 2. Procesamos el guion y generamos los bloques de audio
print("--- Procesando el diálogo interactivo ---")
for i, (personaje, parlamento, hablar_lento) in enumerate(guion):
    # Generamos la voz (usando acento de EE.UU. en español 'es-us' para variar el tono si se desea)
    tts = gTTS(text=parlamento, lang='es', slow=hablar_lento)

    archivo_dialogo = f"dialogo_{i}.mp3"
    tts.save(archivo_dialogo)

    # Desplegamos el resultado de manera ordenada
    print(f"\n👤 {personaje}: \"{parlamento}\"")
    if hablar_lento:
        print("*(Hablando en modo pausado...)*")
    display(Audio(archivo_dialogo, autoplay=False))

!pip install edge-tts

import asyncio
import edge_tts
from IPython.display import Audio, display

# 1. Guion con nombres de voces actualizados y verificados
guion = [
    {
        "personaje": "Profesor (Voz Masculina)",
        "texto": "Hola a todos. Hoy analizaremos el comportamiento de los algoritmos estocásticos.",
        "voz": "es-MX-JorgeNeural"  # Voz masculina estándar garantizada
    },
    {
        "personaje": "Estudiante (Voz Femenina)",
        "texto": "Profesor, ¿podríamos usar un modelo de Markov para predecir el clima como Iracheta?",
        "voz": "es-MX-DaliaNeural"  # Voz femenina estándar garantizada
    },
    {
        "personaje": "Profesor (Voz Masculina)",
        "texto": "Excelente pregunta. De hecho, un Modelo Oculto de Markov es perfecto para eso.",
        "voz": "es-MX-JorgeNeural"
    }
]

# 2. Función asíncrona con manejo seguro de flujo
async def generar_dialogo_seguro():
    print("--- Procesando diálogo con voces neuronales de Microsoft ---")
    for i, line in enumerate(guion):
        archivo_salida = f"dialogo_neural_{i}.mp3"

        try:
            # Crear la comunicación con el servicio de Edge
            communicate = edge_tts.Communicate(line["texto"], line["voz"])
            # Guardar de manera asíncrona
            await communicate.save(archivo_salida)

            # Desplegar los resultados en la libreta si el archivo se creó con éxito
            print(f"\n👤 {line['personaje']}: \"{line['texto']}\"")
            display(Audio(archivo_salida, autoplay=False))

        except Exception as err:
            print(f"\n❌ Error al generar la voz para {line['personaje']}: {err}")

# 3. Ejecución directa en Colab
await generar_dialogo_seguro()

"""# Desafío

Escribe el código para que la voz artificial diga el lema de la UNAM en 4 idiomas e intercaladamente voz de hombre y mujer.
"""

import asyncio
import edge_tts
from IPython.display import Audio, display

frases_multilingues = [
    {
        "idioma": "Español",
        "texto": "Por mi raza hablará el espíritu.",
        "voz": "es-MX-DaliaNeural",   # Femenina
        "tipo": "Voz Femenina"
    },
    {
        "idioma": "Inglés",
        "texto": "The spirit will speak for my race.",
        "voz": "en-US-GuyNeural",     # Masculina
        "tipo": "Voz Masculina"
    },
    {
        "idioma": "Francés",
        "texto": "L'esprit parlera pour ma race.",
        "voz": "fr-FR-DeniseNeural",  # Femenina
        "tipo": "Voz Femenina"
    },
    {
        "idioma": "Japonés",
        "texto": "精霊が我が民族を代表して語るだろう。",
        "voz": "ja-JP-KeitaNeural",   # Masculina
        "tipo": "Voz Masculina"
    }
]


async def generar_audios_multilingues():

    for i, frase in enumerate(frases_multilingues):

        archivo_salida = f"audio_{i}.mp3"

        try:
            # Crear comunicación con Edge TTS
            communicate = edge_tts.Communicate(
                text=frase["texto"],
                voice=frase["voz"]
            )

            # Guardar archivo
            await communicate.save(archivo_salida)

            # Mostrar resultados
            print(f"\n Idioma: {frase['idioma']}")
            print(f" {frase['tipo']}")
            print(f" Texto: {frase['texto']}")

            display(Audio(archivo_salida, autoplay=False))

        except Exception as err:
            print(f"\n❌ Error en {frase['idioma']}: {err}")

await generar_audios_multilingues()

"""#Conclusión

En esta práctica se utilizaron herramientas de Text To Speech como **gTTS** y **edge-tts** para generar voces artificiales en distintos idiomas y estilos. Se aprendió a crear audios automáticos, diálogos interactivos y voces neuronales más naturales utilizando Python. Además, se observó cómo la inteligencia artificial puede aplicarse en educación, accesibilidad y asistentes virtuales, facilitando una comunicación más dinámica e inclusiva.

<hr/>
<footer style="text-align:center; font-size:12px; color:gray;">
© 2026 UNAM Facultado de Ciencias – Todos los derechos reservados

</footer>
"""